import pandas as pd
df=pd.read_csv("cleaned_students.csv")
print(df.head())
print(df.columns)
print(df.shape[0])
print(df.shape[1])
print(df.dtypes)
print(df.describe())
print("average marks",df["MARKS"].mean())
print("highest marks",df["MARKS"].max())
print("minimum value",df["MARKS"].min())
print("total number of students",len(df))
print(df["CITY"].value_counts())
print(df.groupby("CITY")["MARKS"].mean())
print(df.groupby("AGE")["MARKS"].mean())
print(df.groupby("NAME")["MARKS"].mean())
Q1=df["MARKS"].quantile(0.25)
Q3=df["MARKS"].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3-1.5*IQR
outliers=df[(df["MARKS"]<lower)|(df["MARKS"]>upper)]
print("Q1",Q1)
print("Q2",Q3)
print("IQR",IQR)
print("LOWER LIMIT",lower)
print("UPPER LIMIT",upper)
print("outliers")
print(outliers)
print("age values")
print(df["AGE"])
print("MARKS VALUES")
print(df["MARKS"])
print(df[["AGE","MARKS"]])

